// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admin_service.proto

package typesconnect

import (
	context "context"
	errors "errors"
	types "github.com/aergoio/aergo/types"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "service.AdminService"
)

// AdminServiceClient is a client for the service.AdminService service.
type AdminServiceClient interface {
	Keygen(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
	Mempool(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
	Sign(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
	Vote(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
}

// NewAdminServiceClient constructs a client for the service.AdminService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &adminServiceClient{
		keygen: connect_go.NewClient[types.Empty, types.Empty](
			httpClient,
			baseURL+"/service.AdminService/Keygen",
			opts...,
		),
		mempool: connect_go.NewClient[types.Empty, types.Empty](
			httpClient,
			baseURL+"/service.AdminService/Mempool",
			opts...,
		),
		sign: connect_go.NewClient[types.Empty, types.Empty](
			httpClient,
			baseURL+"/service.AdminService/Sign",
			opts...,
		),
		vote: connect_go.NewClient[types.Empty, types.Empty](
			httpClient,
			baseURL+"/service.AdminService/Vote",
			opts...,
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	keygen  *connect_go.Client[types.Empty, types.Empty]
	mempool *connect_go.Client[types.Empty, types.Empty]
	sign    *connect_go.Client[types.Empty, types.Empty]
	vote    *connect_go.Client[types.Empty, types.Empty]
}

// Keygen calls service.AdminService.Keygen.
func (c *adminServiceClient) Keygen(ctx context.Context, req *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return c.keygen.CallUnary(ctx, req)
}

// Mempool calls service.AdminService.Mempool.
func (c *adminServiceClient) Mempool(ctx context.Context, req *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return c.mempool.CallUnary(ctx, req)
}

// Sign calls service.AdminService.Sign.
func (c *adminServiceClient) Sign(ctx context.Context, req *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return c.sign.CallUnary(ctx, req)
}

// Vote calls service.AdminService.Vote.
func (c *adminServiceClient) Vote(ctx context.Context, req *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return c.vote.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the service.AdminService service.
type AdminServiceHandler interface {
	Keygen(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
	Mempool(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
	Sign(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
	Vote(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/service.AdminService/Keygen", connect_go.NewUnaryHandler(
		"/service.AdminService/Keygen",
		svc.Keygen,
		opts...,
	))
	mux.Handle("/service.AdminService/Mempool", connect_go.NewUnaryHandler(
		"/service.AdminService/Mempool",
		svc.Mempool,
		opts...,
	))
	mux.Handle("/service.AdminService/Sign", connect_go.NewUnaryHandler(
		"/service.AdminService/Sign",
		svc.Sign,
		opts...,
	))
	mux.Handle("/service.AdminService/Vote", connect_go.NewUnaryHandler(
		"/service.AdminService/Vote",
		svc.Vote,
		opts...,
	))
	return "/service.AdminService/", mux
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) Keygen(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("service.AdminService.Keygen is not implemented"))
}

func (UnimplementedAdminServiceHandler) Mempool(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("service.AdminService.Mempool is not implemented"))
}

func (UnimplementedAdminServiceHandler) Sign(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("service.AdminService.Sign is not implemented"))
}

func (UnimplementedAdminServiceHandler) Vote(context.Context, *connect_go.Request[types.Empty]) (*connect_go.Response[types.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("service.AdminService.Vote is not implemented"))
}
